// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qynetmxkikxahftnhefo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5bmV0bXhraWt4YWhmdG5oZWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2Mzg2MzcsImV4cCI6MjA1MDIxNDYzN30.X_UITs3LS4I2bNDcn-wx9R6JnZ7ZzH00L8VqcZV6t8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);